development:
  clients:
    default:
      database: b2c-api
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: b2c-api-test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
